---
name: 'Deploy website to GitHub Pages'

on:
  push:
    branches:
      - 'dev'
      # TODO: remove once the workflow is verified
      - 'feature/deploy-website-to-github-pages'

permissions: {}

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7
      - uses: 'atsphinx/.github/actions/setup-aqua@main'
      - name: 'Configure dependencies'
        run: |
          bun install
      - name: 'Build theme package'
        run: |
          bun run --cwd=packages/themes build
      - name: 'Build website'
        run: |
          bun run --cwd=apps/website build
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: 'apps/website/_site'
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: 'github-pages'
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
