---
name: 'Deploy website to GitHub Pages as mirror'

on:
  push:
    branches:
      - 'dev'

permissions: {}

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: 'atsphinx/.github/actions/setup-aqua@main'
      - name: 'Configure dependencies'
        run: |
          bun install
      - name: 'Build theme package'
        run: |
          bun run --cwd=packages/themes build
      - name: 'Build website'
        run: |
          bun run --cwd=apps/website build
        env:
          PRODUCTION_FQDN: 'attakei-lab.github.io'
          PRODUCTION_PATH: '/bulma-themes'
      - uses: actions/configure-pages@v6
      - uses: actions/upload-pages-artifact@v5
        with:
          path: 'apps/website/_site'
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: 'github-pages'
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v5
